"""create agency registry tables

Revision ID: 01dcc9e5d8c1
Revises: 
Create Date: 2026-02-20 09:43:30.472606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '01dcc9e5d8c1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('canonical_name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('agency_type', sa.Enum('municipal_pd', 'sheriff', 'district_attorney', 'campus', 'transit', 'state', 'federal_task_force', 'coroner', 'other', name='agencytype'), nullable=False),
    sa.Column('homepage_url', sa.String(), nullable=True),
    sa.Column('platform_type', sa.String(), nullable=True),
    sa.Column('parser_id', sa.String(), nullable=True),
    sa.Column('scrape_frequency', sa.String(), nullable=False),
    sa.Column('has_activity_data', sa.Boolean(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.Column('foia_contact', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('agency_id')
    )
    op.create_table('agency_feeds',
    sa.Column('feed_id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('feed_type', sa.Enum('press_releases', 'daily_activity_log', 'arrest_log', 'incident_reports', 'transparency_portal', 'crimemapping_embed', 'community_alerts', 'rss_feed', 'open_data_api', 'pdf_library', name='feedtype'), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.Column('last_successful', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.agency_id'], ),
    sa.PrimaryKeyConstraint('feed_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agency_feeds')
    op.drop_table('agencies')
    # ### end Alembic commands ###
